---
booktitle: Proceedings of the 11th Machine Learning for Healthcare Conference
shortname: MLHC
year: '2026'
volume: '340'
start: &1 2026-08-12
end: 2026-08-14
published: 2026-09-08
conference_number: '11'
layout: proceedings
series: Proceedings of Machine Learning Research
publisher: PMLR
issn: 2640-3498
id: MLHC-2026
month: 0
cycles: false
bibtex_editor: Krishnan, Rahul G. and van Amsterdam, Wouter A. C. and Chopra, Sumit
  and Overgaard, Shauna and Hughes, Michael and \"{O}tle\c{s}, Erkin and Shen, Yiqiu
  and Shanmugam, Divya and Nayan, Madhur and Engelhard, Matthew and Fackler, Jim and
  Oberst, Michael
editor:
- given: Rahul G.
  family: Krishnan
- given: Wouter A. C.
  family: Amsterdam
  prefix: van
- given: Sumit
  family: Chopra
- given: Shauna
  family: Overgaard
- given: Michael
  family: Hughes
- given: Erkin
  family: Ötleş
- given: Yiqiu
  family: Shen
- given: Divya
  family: Shanmugam
- given: Madhur
  family: Nayan
- given: Matthew
  family: Engelhard
- given: Jim
  family: Fackler
- given: Michael
  family: Oberst
title: Proceedings of Machine Learning Research
description: |
  Proceedings of the 11th Machine Learning for Healthcare Conference
    Held in The Johns Hopkins University School of Medicine, Baltimore, MD, USA on 12-14 August 2026

  Published as Volume 340 by the Proceedings of Machine Learning Research on 08 September 2026.

  Volume Edited by:
    Rahul G. Krishnan
    Wouter A. C. van Amsterdam
    Sumit Chopra
    Shauna Overgaard
    Michael Hughes
    Erkin Ötleş
    Yiqiu Shen
    Divya Shanmugam
    Madhur Nayan
    Matthew Engelhard
    Jim Fackler
    Michael Oberst

  Series Editors:
    Tegan Emerson
    Hoel Kervadec
    Neil D. Lawrence
date_str: 12--14 Aug
url: https://proceedings.mlr.press
author:
  name: PMLR
baseurl: "/v340"
twitter_username: MLResearchPress
github_username: mlresearch
markdown: kramdown
exclude:
- README.md
- Gemfile
- ".gitignore"
plugins:
- jekyll-feed
- jekyll-seo-tag
- jekyll-remote-theme
remote_theme: mlresearch/jekyll-theme
style: pmlr
permalink: "/:title.html"
ghub:
  edit: true
  repository: v340
display:
  copy_button:
    bibtex: true
    endnote: true
    apa: true
  comments: false
volume_type: Volume
volume_dir: v340
email: ''
conference:
  name: Machine Learning for Healthcare Conference
  url: https://mlhc.org
  location: The Johns Hopkins University School of Medicine, Baltimore, MD, USA
  dates:
  - *1
  - 2026-08-13
  - 2026-08-14
analytics:
  google:
    tracking_id: UA-92432422-1
link_visibility:
  openreview: true
  pdf: true
  supplementary: true
  software: true
  video: true
  arxiv: true
  doi: true
  website: true
orig_bibfile: mlhc26_clean.bib
# Site settings
# Original source:  mlhc26_clean.bib
